return {
    ensure_installed = {
        "arduino",
        "c",
        "cpp",
        "c_sharp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "elixir",
        "embedded_template", -- ejs, erb (not maintaned)
        "go",
        "haskell",
        "html",
        "htmldjango",
        "ini",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "kconfig",
        "kotlin",
        "latex",
        "lua",
        "luau",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "meson",
        "ninja",
        "nix",
        "php",
        "python",
        "ruby",
        "rust",
        "smali",
        "solidity",
        "sql",
        "svelte",
        "toml",
        "typescript",
        "v",
        "vim",
        "vue",
        "xml",
        "yaml",
        "zig",
    },
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
